question_data = [
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Geography",
        "question": "The Sonoran Desert is located in eastern Africa.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Geography",
        "question": "There exists an island named &quot;Java&quot;.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Geography",
        "question": "Norway has a larger land area than Sweden.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Geography",
        "question": "Seoul is the capital of North Korea.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Geography",
        "question": "There are no roads in/out of Juneau, Alaska.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Geography",
        "question": "Israel is 7 hours ahead of New York.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Geography",
        "question": "The Southeast Asian island of Borneo is politically divided among 3 countries.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Geography",
        "question": "Is Tartu the capital of Estonia?",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Geography",
        "question": "The longest place named in the United States is Lake Chargoggagoggmanchauggagoggchaubunagungamaugg, located near Webster, MA.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Geography",
        "question": "&quot;Mongolia&quot; was a part of the now non-existent U.S.S.R.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Geography",
        "question": "The flag of South Africa features 7 colours.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Geography",
        "question": "Antarctica is the largest desert in the world.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Geography",
        "question": "Vietnam is the only country in the world that starts with V. ",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Geography",
        "question": "You could walk from Norway to North Korea while only passing through Russia.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Geography",
        "question": "The capital of the US State Ohio is the city of Chillicothe.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Geography",
        "question": "Japan has left-hand side traffic.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Geography",
        "question": "Liechtenstein does not have an airport.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Geography",
        "question": "The surface area of Russia is slightly larger than that of the dwarf planet Pluto.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Geography",
        "question": "The title of the 1969 film &quot;Krakatoa, East_of Java&quot; is incorrect, as Krakatoa is in fact west of Java.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Geography",
        "question": "Gothenburg is the capital of Sweden.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
]
